### PR TITLE
Updates to work on v1.16.x

### PR DESCRIPTION
**Pull request by Starystars67**
Updated to work with v1.16.0.

The icon will require font-awesome to be updated to support brands. Can we do this as a whole for nodebb?

### CODE REVIEW

**Comment by julianlam** [comment]
Thanks. LGTM, although as you say, the icon does not show up due to our older FontAwesome library. We're unable to upgrade to FontAwesome 4 (or 5) because there are some breaking changes that mean every icon in use would break (plugins included, etc.)

In the meantime, we currently override the icons with custom styling in our Facebook and Google plugins (due to branding guidelines), so we could do something similar here.

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-sso-facebook/blob/master/static/lib/main.js

**Comment by Starystars67** [comment]
I see, I think something like that could be done yeah!

Out of curiosity If I made PR's for most of the / all the default plugins for NodeBB would this be accepted? 
I ask now before making the effort to be potentially denied.

**Comment by julianlam** [comment]
We'll certainly review them all, of course :smile: Simple fixes like compatibility fixes like yours are well appreciated.

**Comment by aoor9** [comment]
Seems that FA is finally upgraded to version 5 on NodeBB since [v1.18.0](https://github.com/NodeBB/NodeBB/blob/05032ca2c09560c96f7c45cefd2f852263e4abb3/CHANGELOG.md#v1180-2021-08-25). So will you please merge this request (and close [this](https://github.com/julianlam/nodebb-plugin-sso-patreon/issues/1#issue-220161555) related issue)? I want to make a pull request, too.

**Comment by julianlam** [comment]
@aoor9 Ah, yes! Sorry :smile:

**Pull request merged**
